# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - name: OE setup | Set installer URLs from the OE storage account
      set_fact:
        intel_psw_url:       "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20PSW%20for%20Windows%20v2.12.103.1.exe"
        intel_psw_hash:      "FD3ED08C70DB35B122F2FDD8E6046E3A97B078F4735705CDC074767F040A5609"
        intel_dcap_url:      "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20DCAP%20for%20Windows%20v1.10.103.1.exe"
        intel_dcap_hash:     "2AB16BB499DE29D9EE7A5F74A79902EF69169D37704167611748F9E281B9E46A"
        git_url:             "https://oejenkins.blob.core.windows.net/oejenkins/Git-2.31.1-64-bit.exe"
        git_hash:            "C43611EB73AD1F17F5C8CC82AE51C3041A2E7279E0197CCF5F739E9129CE426E"
        seven_zip_url:       "https://oejenkins.blob.core.windows.net/oejenkins/7z1806-x64.msi"
        seven_zip_hash:      "F00E1588ED54DDF633D8652EB89D0A8F95BD80CCCFC3EED362D81927BEC05AA5"
        vs_buildtools:       "https://oejenkins.blob.core.windows.net/oejenkins/vs_buildtools_2017.exe"
        vs_buildtools_hash:  "9822B4C851E14D9658BABD1533F66F518C6169196E985FE5713B2774128832AE"
        clang_url:           "https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe"
        clang_hash:          "893f8a12506f8ad29ca464d868fb432fdadd782786a10655b86575fc7fc1a562"
        shellcheck_url:      "https://oejenkins.blob.core.windows.net/oejenkins/shellcheck-v0.7.0.zip"
        shellcheck_hash:     "02CFA14220C8154BB7C97909E80E74D3A7FE2CBB7D80AC32ADCAC7988A95E387"
        nuget_url:           "https://oejenkins.blob.core.windows.net/oejenkins/nuget-3.4.3.nupkg"
        nuget_hash:          "2D4D38666E5C7D27EE487C60C9637BD9DD63795A117F0E0EDC68C55EE6DFB71F"
        devcon_package_url:  "https://oejenkins.blob.core.windows.net/oejenkins/devcon_package.cab"
        devcon_package_hash: "A38E409617FC89D0BA1224C31E42AF4344013FEA046D2248E4B9E03F67D5908A"
        az_dcap_client_url:  "https://oejenkins.blob.core.windows.net/oejenkins/microsoft.azure.dcap.1.10.0.nupkg"
        az_dcap_client_hash: "4B416DA557C1102CBC9FFD5D39B6B344762F8DFD17BA2BB0D0EDC0ACABE2C06B"
        nsis_url:            "https://oejenkins.blob.core.windows.net/oejenkins/nsis-3.05-setup.exe"
        nsis_hash:           "1A3CC9401667547B9B9327A177B13485F7C59C2303D4B6183E7BC9E6C8D6BFDB"

    - name: OE setup | Run the install-windows-prereqs.ps1 script (this may take a while)
      script: ../install-windows-prereqs.ps1
        -InstallPath         "C:\oe_prereqs"
        -LaunchConfiguration "{{ launch_configuration }}"
        -DCAPClientType      "Azure"
        -IntelPSWURL         "{{ intel_psw_url }}"
        -IntelPSWHash        "{{ intel_psw_hash }}"
        -IntelDCAPURL        "{{ intel_dcap_url }}"
        -IntelDCAPHash       "{{ intel_dcap_hash }}"
        -GitURL              "{{ git_url }}"
        -GitHash             "{{ git_hash }}"
        -SevenZipURL         "{{ seven_zip_url }}"
        -SevenZipHash        "{{ seven_zip_hash }}"
        -VSBuildToolsURL     "{{ vs_buildtools }}"
        -VSBuildToolsHash    "{{ vs_buildtools_hash }}"
        -ClangURL            "{{ clang_url }}"
        -ClangHash           "{{ clang_hash }}"
        -ShellCheckURL       "{{ shellcheck_url }}"
        -ShellCheckHash      "{{ shellcheck_hash }}"
        -NugetURL            "{{ nuget_url }}"
        -NugetHash           "{{ nuget_hash }}"
        -DevconURL           "{{ devcon_package_url }}"
        -DevconHash          "{{ devcon_package_hash }}"
        -AzureDCAPNupkgURL   "{{ az_dcap_client_url }}"
        -AzureDCAPNupkgHash  "{{ az_dcap_client_hash }}"
        -NSISURL             "{{ nsis_url }}"
        -NSISHash            "{{ nsis_hash }}"
        -InstallDocker

     # One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups

    - name: OE setup | Reboot the node
      win_reboot:

    - import_role:
        name: windows/openenclave
        tasks_from: validation.yml
