name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup
      run: echo ${{ secrets.SECRET }}

