name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:nightly
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: edgelessrt
        submodules: recursive

    - name: Setup
      run: mkdir build

    - name: Build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ../edgelessrt
        ninja
      working-directory: build

    - name: Test
      run: |
        OE_SIMULATION=1 ctest --output-on-failure -E "tests/crypto/|tests/ert/ttls"
      working-directory: build

    - name: CPack
      run: cpack -G DEB
      working-directory: build

    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: edgelessrt
        path: build/*.deb

    - name: Deploy edgelessrt-dev:nightly
      if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.CI_GITHUB_REPOSITORY }}" \
        -d '{"event_type": "docker-build",
            "client_payload":{"repository":"edgelessrt",
                              "sign":"nightly",
                              "imagename":"edgelessrt-dev",
                              "tag":"nightly",
                              "file": "dockerfiles/Dockerfile",
                              "args": "--build-arg erttag=master",
                              "target":"release_develop"}}' \
        https://api.github.com/repos/edgelesssys/deployment/dispatches

    - name: Deploy edgelessrt-deploy:nightly
      if: github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.CI_GITHUB_REPOSITORY }}" \
        -d '{"event_type": "docker-build",
            "client_payload":{"repository":"edgelessrt",
                              "sign":"nightly",
                              "imagename":"edgelessrt-deploy",
                              "tag":"nightly",
                              "file": "dockerfiles/Dockerfile",
                              "args": "--build-arg erttag=master",
                              "target":"release_deploy"}}' \
        https://api.github.com/repos/edgelesssys/deployment/dispatches
